### PR TITLE
add attributes for ref id

### PR DESCRIPTION
**Pull request by websupporter**
With this pull request you could use `[amazon-suche id="Partner ID"]`

### CODE REVIEW

**Comment by pixolin** [comment]
Oh well, I could even think of more attributes to cover the various settings you can select [in the form provided by Amazon](https://partnernet.amazon.de/gp/associates/promo/search-widget.html).

Out of curiosity: 
Why wouldn't you use function `shortcode_atts()` provided by WordPress? 
And what about escaping?

**Comment by websupporter** [comment]
havent thought about it XD

**Comment by pixolin** [comment]
I guess the difference is, I keep reading in the Codex how it should work while you already know and just code along. Guess who is faster? :blush:

**Comment by websupporter** [comment]
Guess who does best practice :smile:

**Comment by websupporter** [comment]
:dancer: ;)

**Pull request merged**
